apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  # clusterName is required if you want to use ClusterSelectors and must be
  # unique among all managed clusters
  clusterName: gke-config-sync-vol2
  # Enable multi-repo mode to use additional features
  enableMultiRepo: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: twistlock