apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  git:
    repo: git@github.com:ici-labs/gke-config-sync.git
    auth: ssh
    dir: foo-corp
    branch: main
    secretRef:
      name: git-creds